print("\n")
print("Welcome to my Mad Libs Game. Have fun playing!")
print("\n")
color_1 =  input("Enter a color: ")
color_2 = input("Enter a second color: ")
color_3 =  input("Enter a third color: ")
color_4 = input("Enter a forth color: ")
print("\n")
print("Here you go... :) :) :)")
print("Roses are " + color_1)
print("Grasses are " +  color_2)
print("Sky is " + color_3)
print("Poop is " +  color_4)
# print("Sugar is sweet")
# rint("And so are you")